sourmash:
  # The k-mer size(s) you'd like to use for profiling.
  ksize: [31, 51]

  # The relative or full path to the sourmash database file(s), for each
  # k-mer size you want to run. These can be downloaded from:
  # https://sourmash.readthedocs.io/en/latest/databases.html 
  search_databases:

    # estimatednumber of base pairs required for a database match.
    # note that this affects runtime and memory. We recommend running
    # with default threshold (50kb) first and then modifying if necessary.
    threshold_bp: 50000

    k31:
      - databases/genbank-2022.03-archaea-k31.zip
      - databases/genbank-2022.03-bacteria-k31.zip
      - databases/genbank-2022.03-fungi-k31.zip
      - databases/genbank-2022.03-protozoa-k31.zip
      - databases/genbank-2022.03-viral-k31.zip
    k51:
      - databases/genbank-2022.03-archaea-k51.zip
      - databases/genbank-2022.03-bacteria-k51.zip
      - databases/genbank-2022.03-fungi-k51.zip
      - databases/genbank-2022.03-protozoa-k51.zip
      - databases/genbank-2022.03-viral-k51.zip

  # The relative or full path to the corresponding lineage file(s) for
  # the sourmash databases specified above. Note that this file is not
  # different per k-mer size. Lineage files can be downloaded from:
  # https://sourmash.readthedocs.io/en/latest/databases.html 
  database_lineage_files:
    - databases/genbank-2022.03-archaea.lineages.csv.gz
    - databases/genbank-2022.03-bacteria.lineages.csv.gz
    - databases/genbank-2022.03-fungi.lineages.csv.gz
    - databases/genbank-2022.03-protozoa.lineages.csv.gz
    - databases/genbank-2022.03-viral.lineages.csv.gz

  # sourmash is not multi-threaded so this is default set to 1.
  # There may be cases where changing thread number helps with
  # HPC resource allocation. The sourmash_gather step in particular
  # can require substantial memory, and this thread number will only 
  # be applied to that rule.
  threads: 1